server:
  port: 8888

debug: false

name: chendong

student:
  name: chendong
  age: 18


student2: {name: chendong,age: 18}

pets:
  - cat
  - dog
  - pig

pets2: [cat,dog,pig]


person:
  name: chendong
  age: 18
  happy: true
  birth: 1888/08/18
  maps: {k1: v1,k2: v2}
  lists:
    - code
    - music
    - girl
  dog:
    name: wangcai
    age: 5
